In [3]:
import mysql.connector
import pandas as pd

In [2]:
import sys
print(sys.executable)

c:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [4]:
conn = mysql.connector.connect(
    user = 'root',
    password = 'root',
    host = '127.0.0.1',
    port = 3306,
    database = 'the_kiran_academy_db'
)
print("Connection successfull ..")

Connection successfull ..

In [5]:
st1 = "select * from students"
st2 = "select * from courses"
st3 = "select * from branch"
students = pd.read_sql(st1,conn)
students

C:\Users\Admin\AppData\Local\Temp\ipykernel_25096\1363201278.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  students = pd.read_sql(st1,conn)

    student_id     student_name  br_id  course_id  paid_fee
0            1      Aarav Patil      1        101     15000
1            2     Rohan Sharma      2        102     20000
2            3   Priya Deshmukh      3        103     25000
3            4      Sneha Joshi      4        104     30000
4            5        Om Jadhav      1        102     18000
..         ...              ...    ...        ...       ...
95          96      Anuja Joshi      4        102     21000
96          97   Prashant Patil      1        103     29000
97          98       Tejal More      2        104     45000
98          99  Ravindra Jadhav      3        101     16000
99         100       Swati Kale      4        102     24000

[100 rows x 5 columns]

In [6]:
courses = pd.read_sql(st2,conn)
courses

C:\Users\Admin\AppData\Local\Temp\ipykernel_25096\2474501047.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  courses = pd.read_sql(st2,conn)

   course_id        course_name  duration   fees
0        101  Python Full Stack  6 Months  30000
1        102    Java Full Stack  6 Months  30000
2        103     Data Analytics  5 Months  40000
3        104       Data Science  8 Months  50000

In [7]:
branch = pd.read_sql(st3,conn)
branch

C:\Users\Admin\AppData\Local\Temp\ipykernel_25096\2096206350.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  branch = pd.read_sql(st3,conn)

   br_id      br_name
0      1  Karve Nagar
1      2     Hadapsar
2      3    Chinchwad
3      4       Nagpur

In [31]:
df1 = pd.merge(students,branch,how="inner",on="br_id")
df2 = pd.merge(df1,courses,how="inner",on="course_id")
student_data = df2[['student_id','student_name','br_name','course_name','duration','fees','paid_fee']]

In [32]:
student_data

,student_id,student_name,br_name,course_name,duration,fees,paid_fee
0,1,Aarav Patil,Karve Nagar,Python Full Stack,6 Months,30000,15000
1,2,Rohan Sharma,Hadapsar,Java Full Stack,6 Months,30000,20000
2,3,Priya Deshmukh,Chinchwad,Data Analytics,5 Months,40000,25000
3,4,Sneha Joshi,Nagpur,Data Science,8 Months,50000,30000
4,5,Om Jadhav,Karve Nagar,Java Full Stack,6 Months,30000,18000
...,...,...,...,...,...,...,...
95,96,Anuja Joshi,Nagpur,Java Full Stack,6 Months,30000,21000
96,97,Prashant Patil,Karve Nagar,Data Analytics,5 Months,40000,29000
97,98,Tejal More,Hadapsar,Data Science,8 Months,50000,45000
98,99,Ravindra Jadhav,Chinchwad,Python Full Stack,6 Months,30000,16000
99,100,Swati Kale,Nagpur,Java Full Stack,6 Months,30000,24000

In [33]:
student_data['remaining_fee'] = student_data['fees'] - student_data['paid_fee']
student_data

C:\Users\Admin\AppData\Local\Temp\ipykernel_25096\2145191233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student_data['remaining_fee'] = student_data['fees'] - student_data['paid_fee']

,student_id,student_name,br_name,course_name,duration,fees,paid_fee,remaining_fee
0,1,Aarav Patil,Karve Nagar,Python Full Stack,6 Months,30000,15000,15000
1,2,Rohan Sharma,Hadapsar,Java Full Stack,6 Months,30000,20000,10000
2,3,Priya Deshmukh,Chinchwad,Data Analytics,5 Months,40000,25000,15000
3,4,Sneha Joshi,Nagpur,Data Science,8 Months,50000,30000,20000
4,5,Om Jadhav,Karve Nagar,Java Full Stack,6 Months,30000,18000,12000
...,...,...,...,...,...,...,...,...
95,96,Anuja Joshi,Nagpur,Java Full Stack,6 Months,30000,21000,9000
96,97,Prashant Patil,Karve Nagar,Data Analytics,5 Months,40000,29000,11000
97,98,Tejal More,Hadapsar,Data Science,8 Months,50000,45000,5000
98,99,Ravindra Jadhav,Chinchwad,Python Full Stack,6 Months,30000,16000,14000
99,100,Swati Kale,Nagpur,Java Full Stack,6 Months,30000,24000,6000

In [34]:

total_sale = student_data['fees'].sum()
collection = student_data['paid_fee'].sum()
remaining = student_data['remaining_fee'].sum()
remaining

np.int64(1099000)

In [35]:
gp = student_data.groupby(by="br_name")
gp['paid_fee'].sum()

br_name
Chinchwad      443000
Hadapsar       927000
Karve Nagar    708000
Nagpur         573000
Name: paid_fee, dtype: int64

In [36]:
course_by = student_data.groupby(by="course_name")
course_by['remaining_fee'].sum()

course_name
Data Analytics       322000
Data Science         226000
Java Full Stack      195000
Python Full Stack    356000
Name: remaining_fee, dtype: int64